name: gestao_eventos
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  adaptive_dialog: ^2.1.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.17.0
  device_preview: ^1.1.0
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gutter: ^1.0.0
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.7
  getwidget: ^4.0.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  image_picker_web: ^3.1.1
  intl: ^0.18.0
  loader_overlay: ^4.0.0
  modal_bottom_sheet: ^2.1.2
  smooth_page_indicator: ^1.1.0
  uuid: ^4.3.2

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/imgs/eventos/pedidos/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
