// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7hRt-3Fa0DmAKYKlc3JILfCqXkhYV-bs',
    appId: '1:606815910887:web:b56fc4b92dde18323e9b42',
    messagingSenderId: '606815910887',
    projectId: 'gestao-evento',
    authDomain: 'gestao-evento.firebaseapp.com',
    storageBucket: 'gestao-evento.appspot.com',
    measurementId: 'G-2TJWKMT7KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8u-Ww3KXUrLCYHueVpzBd3iAallQuiJ8',
    appId: '1:606815910887:android:5fe9edb09ea7b0b73e9b42',
    messagingSenderId: '606815910887',
    projectId: 'gestao-evento',
    storageBucket: 'gestao-evento.appspot.com',
  );
}
